//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CapNhatDHs = new HashSet<CapNhatDH>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public string MaDH { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public string GhiChu { get; set; }
        public string PTThanhToan { get; set; }
        public Nullable<int> TongTienSP { get; set; }
        public Nullable<int> PhiShip { get; set; }
        public string MaKH { get; set; }
        public string MaGiamGia { get; set; }
        public string IDTrangThai { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapNhatDH> CapNhatDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
