//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopTT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSHOPTHOITRANGEntities : DbContext
    {
        public QLSHOPTHOITRANGEntities()
            : base("name=QLSHOPTHOITRANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhSanPham> AnhSanPhams { get; set; }
        public virtual DbSet<CapNhatDH> CapNhatDHs { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<XuLySanPham> XuLySanPhams { get; set; }
        public virtual DbSet<View_DonHangByMaDH> View_DonHangByMaDH { get; set; }
    
        public virtual ObjectResult<CheckMaGiamGia_Result> CheckMaGiamGia(string magiamgia)
        {
            var magiamgiaParameter = magiamgia != null ?
                new ObjectParameter("magiamgia", magiamgia) :
                new ObjectParameter("magiamgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckMaGiamGia_Result>("CheckMaGiamGia", magiamgiaParameter);
        }
    
        public virtual int ConfirmDatHang(string maDH, string trangthai, Nullable<System.DateTime> ngaydathang, string ghichu, string ptthanhtoan, Nullable<int> phiship, string magiamgia, string diachi, Nullable<int> tongtiensp, ObjectParameter isSuccess)
        {
            var maDHParameter = maDH != null ?
                new ObjectParameter("maDH", maDH) :
                new ObjectParameter("maDH", typeof(string));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var ngaydathangParameter = ngaydathang.HasValue ?
                new ObjectParameter("ngaydathang", ngaydathang) :
                new ObjectParameter("ngaydathang", typeof(System.DateTime));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var ptthanhtoanParameter = ptthanhtoan != null ?
                new ObjectParameter("ptthanhtoan", ptthanhtoan) :
                new ObjectParameter("ptthanhtoan", typeof(string));
    
            var phishipParameter = phiship.HasValue ?
                new ObjectParameter("phiship", phiship) :
                new ObjectParameter("phiship", typeof(int));
    
            var magiamgiaParameter = magiamgia != null ?
                new ObjectParameter("magiamgia", magiamgia) :
                new ObjectParameter("magiamgia", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var tongtienspParameter = tongtiensp.HasValue ?
                new ObjectParameter("tongtiensp", tongtiensp) :
                new ObjectParameter("tongtiensp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmDatHang", maDHParameter, trangthaiParameter, ngaydathangParameter, ghichuParameter, ptthanhtoanParameter, phishipParameter, magiamgiaParameter, diachiParameter, tongtienspParameter, isSuccess);
        }
    
        public virtual int CreateChiTietDonHang(string maCTDH, string maSP, string maDH, Nullable<int> soLuongDat, ObjectParameter isSuccess)
        {
            var maCTDHParameter = maCTDH != null ?
                new ObjectParameter("maCTDH", maCTDH) :
                new ObjectParameter("maCTDH", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(string));
    
            var maDHParameter = maDH != null ?
                new ObjectParameter("maDH", maDH) :
                new ObjectParameter("maDH", typeof(string));
    
            var soLuongDatParameter = soLuongDat.HasValue ?
                new ObjectParameter("soLuongDat", soLuongDat) :
                new ObjectParameter("soLuongDat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateChiTietDonHang", maCTDHParameter, maSPParameter, maDHParameter, soLuongDatParameter, isSuccess);
        }
    
        public virtual int CreateDonHang(string maDH, string maKH, Nullable<System.DateTime> ngayDatHang, string ghiChu, string pTThanhToan, Nullable<int> tongTienSP, Nullable<int> phiShip, string maGiamGia, string iDTrangThai, string diaChi, ObjectParameter isSuccess)
        {
            var maDHParameter = maDH != null ?
                new ObjectParameter("maDH", maDH) :
                new ObjectParameter("maDH", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            var ngayDatHangParameter = ngayDatHang.HasValue ?
                new ObjectParameter("ngayDatHang", ngayDatHang) :
                new ObjectParameter("ngayDatHang", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("ghiChu", ghiChu) :
                new ObjectParameter("ghiChu", typeof(string));
    
            var pTThanhToanParameter = pTThanhToan != null ?
                new ObjectParameter("pTThanhToan", pTThanhToan) :
                new ObjectParameter("pTThanhToan", typeof(string));
    
            var tongTienSPParameter = tongTienSP.HasValue ?
                new ObjectParameter("tongTienSP", tongTienSP) :
                new ObjectParameter("tongTienSP", typeof(int));
    
            var phiShipParameter = phiShip.HasValue ?
                new ObjectParameter("phiShip", phiShip) :
                new ObjectParameter("phiShip", typeof(int));
    
            var maGiamGiaParameter = maGiamGia != null ?
                new ObjectParameter("maGiamGia", maGiamGia) :
                new ObjectParameter("maGiamGia", typeof(string));
    
            var iDTrangThaiParameter = iDTrangThai != null ?
                new ObjectParameter("iDTrangThai", iDTrangThai) :
                new ObjectParameter("iDTrangThai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateDonHang", maDHParameter, maKHParameter, ngayDatHangParameter, ghiChuParameter, pTThanhToanParameter, tongTienSPParameter, phiShipParameter, maGiamGiaParameter, iDTrangThaiParameter, diaChiParameter, isSuccess);
        }
    
        public virtual int CreateKhachHang(string maKH, string hoTen, string soDienThoai, string diaChi, string email, string tenDangNhap, string matKhau, ObjectParameter isSuccess)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateKhachHang", maKHParameter, hoTenParameter, soDienThoaiParameter, diaChiParameter, emailParameter, tenDangNhapParameter, matKhauParameter, isSuccess);
        }
    
        public virtual ObjectResult<GetAccoutKhachHang_Result> GetAccoutKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccoutKhachHang_Result>("GetAccoutKhachHang");
        }
    
        public virtual ObjectResult<string> GetAllAnhByMaSP(string maSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllAnhByMaSP", maSPParameter);
        }
    
        public virtual ObjectResult<GetAllDonHang_Result> GetAllDonHang(string iDTrangThai)
        {
            var iDTrangThaiParameter = iDTrangThai != null ?
                new ObjectParameter("iDTrangThai", iDTrangThai) :
                new ObjectParameter("iDTrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDonHang_Result>("GetAllDonHang", iDTrangThaiParameter);
        }
    
        public virtual ObjectResult<GetAllKhachHang_Result> GetAllKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllKhachHang_Result>("GetAllKhachHang");
        }
    
        public virtual ObjectResult<GetAllSanPham_Result> GetAllSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSanPham_Result>("GetAllSanPham");
        }
    
        public virtual ObjectResult<GetCTDonHang_Result> GetCTDonHang(string maDH)
        {
            var maDHParameter = maDH != null ?
                new ObjectParameter("maDH", maDH) :
                new ObjectParameter("maDH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCTDonHang_Result>("GetCTDonHang", maDHParameter);
        }
    
        public virtual int GetDonHangHienTai(string makh, ObjectParameter madh)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDonHangHienTai", makhParameter, madh);
        }
    
        public virtual ObjectResult<GetGioHangKhachHang_Result> GetGioHangKhachHang(string makh)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGioHangKhachHang_Result>("GetGioHangKhachHang", makhParameter);
        }
    
        public virtual ObjectResult<string> GetPhiShip(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetPhiShip", maKHParameter);
        }
    
        public virtual int HuyHoacHoanTra(string madh, string trangthai, string ghichu, ObjectParameter message)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HuyHoacHoanTra", madhParameter, trangthaiParameter, ghichuParameter, message);
        }
    
        public virtual ObjectResult<LoginKhachHang_Result> LoginKhachHang(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginKhachHang_Result>("LoginKhachHang", usernameParameter, passwordParameter);
        }
    
        public virtual int proc_NhanVienLogin(string username, string password, ObjectParameter manv)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_NhanVienLogin", usernameParameter, passwordParameter, manv);
        }
    
        public virtual int RemoveCTDonHang(string maCTDH, ObjectParameter isSuccess)
        {
            var maCTDHParameter = maCTDH != null ?
                new ObjectParameter("maCTDH", maCTDH) :
                new ObjectParameter("maCTDH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveCTDonHang", maCTDHParameter, isSuccess);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateKhachHang(string maKH, string hoTen, string soDienThoai, string diaChi, string email, ObjectParameter isSuccess)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateKhachHang", maKHParameter, hoTenParameter, soDienThoaiParameter, diaChiParameter, emailParameter, isSuccess);
        }
    }
}
