//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DonHangByMaDH
    {
        public string MaDH { get; set; }
        public string MaCTDH { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> TongTienCTDH { get; set; }
        public Nullable<int> SoLuongDat { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> Size { get; set; }
        public string MauSac { get; set; }
    }
}
